In [35]:
import os
import yaml
import pandas as pd

metric_path = "../metric"
metric_list = []
total_num_func = 0
human_num_func = 0
csv_num_func = 0
dl_num_func = 0
# read all the .yaml files in the directory
for dir_name in os.listdir(metric_path):
    # if dir_name.startswith(('csv', 'dl', 'human', 'bcb')) and os.path.isdir(os.path.join(metric_path, dir_name)):
    if dir_name.startswith(('csv', 'dl', 'human')) and os.path.isdir(os.path.join(metric_path, dir_name)):
        # read the .yaml file at dir_name/metric.yaml
        with open(os.path.join(metric_path, dir_name, 'metric.yaml'), 'r') as f:
            metric = yaml.safe_load(f)

        metric['name'] = dir_name
        metric_list.append(metric)

In [18]:
metric_list[0]

{'TMC-list': [{'code': 'def visual_quality(output, ground_truth):\n    from skimage.metrics import structural_similarity as ssim\n    output_image = output[0]  # This would require a method to convert the figure to an image array\n    ground_truth_image = ground_truth[0]  # Assuming the ground truth is also converted to an image array\n    return ssim(output_image, ground_truth_image, multichannel=True)',
   'metric': 'Visual Quality Assessment (e.g., using Structural Similarity Index)',
   'task_name': 'Data visualization'}],
 'prompt': "Draw normal distributions for multiple 'x' and 'y' arrays with labels. Each pair (x, y) represents a different chemical compound in the 'labels' list. The function should output with: tuple(fig: Matplotlib.figure.Figure)\nfig: Matplotlib figure object containing the drawn normal distributions.  \nYou should write self-contained code starting with:  \n```\nimport matplotlib.pyplot as plt\nimport numpy as np\nimport scipy.stats as stats\ndef task_func(x, y, labels):\n```",
 'name': 'bcb659'}

In [19]:
metric_name = dict()
task_name = dict()
for metric in metric_list:
    for tmc in metric['TMC-list']:
        if tmc['metric'] not in metric_name:
            metric_name[tmc['metric']] = {
                "counts": 1,
                "task_dict": {},
                "prompt_list": [],
                "task_id_list": []
            }
            metric_name[tmc['metric']]["task_dict"][tmc['task_name']] = 1
            metric_name[tmc['metric']]["prompt_list"].append(metric['prompt'])
            metric_name[tmc['metric']]["task_id_list"].append(metric['name'])
        else:
            metric_name[tmc['metric']]['counts'] += 1
            if tmc['task_name'] not in metric_name[tmc['metric']]["task_dict"]:
                metric_name[tmc['metric']]["task_dict"][tmc['task_name']] = 1
            else:
                metric_name[tmc['metric']]["task_dict"][tmc['task_name']] += 1
            metric_name[tmc['metric']]["prompt_list"].append(metric['prompt'])
            metric_name[tmc['metric']]["task_id_list"].append(metric['name'])
                
        if tmc['task_name'] not in task_name:
            task_name[tmc['task_name']] = 1
        else:
            task_name[tmc['task_name']] += 1

In [20]:
data = []

for metric, values in metric_name.items():
    for task, count in values["task_dict"].items():
        data.append({
            "Metric": metric,
            "Total Metric Count": values['counts'],  # total count for this metric
            "Task": task,
            "Task Count": count,  # count for this task under the specific metric
            "Prompts": values["prompt_list"],
            "Task ID": values["task_id_list"]
        })

# Convert the list of dictionaries to a DataFrame
df = pd.DataFrame(data)

In [21]:
df.head(3)

,Metric,Total Metric Count,Task,Task Count,Prompts,Task ID
0,"Visual Quality Assessment (e.g., using Structu...",1,Data visualization,1,[Draw normal distributions for multiple 'x' an...,[bcb659]
1,Covariance Matrix Shape,1,Data visualization,1,[Generates a pair plot from a numeric DataFram...,[bcb983]
2,Pair Plot Type,1,Data exploration and statistics understand,1,[Generates a pair plot from a numeric DataFram...,[bcb983]

In [22]:
# df = pd.DataFrame(list(metric_name.items()), columns=['Metric Name', 'Counts'])

# Display only the first 3 entries
df.head(3)

df.to_csv('metric_name_final.csv', index=False)

In [41]:
df = pd.DataFrame(list(task_name.items()), columns=['Task Name', 'Counts'])

# Display only the first 3 entries
df.head(3)

# Display the table
df.to_csv("task_name_counts.csv", index=False)

## Count Functions

In [22]:
task_2_func = {
    "Data cleaning and preprocessing": [
        "Data Cleaning Completeness",
        "DataFrame Shape Validation",
        "Data Completeness",
        "Normalization Range Check",
        "Data Quality Score"
    ],
    "Data exploration and statistics understand": [
        "Data Accuracy",
        "Data Integrity",
        "Data Consistency",
        "Data Validity",
        "Data Uniformity"
    ],
    "Data visualization": [
        "Visualization Completeness",
        "Plot Validity",
        "Visualization Quality",
        "Title Verification",
        "Correlation Coefficient"
    ],
    "Predictive modeling": [
        "Model Accuracy",
        "Mean Absolute Error",
        "R-squared Value",
        "Clustering Validity",
        "Mean Squared Error",
        "Explained Variance Ratio"
    ],
    "Data mining": [
        "Silhouette Score",
        "Clustering Validity",
        "Prediction Accuracy",
        "Association Rule Count",
        "Association Rule Confidence"
    ],
    "Pattern recognition": [
        "Silhouette Score",
        "Completeness",
        "Pattern Recognition Validity",
        "Pattern Recognition Accuracy",
        "Pattern Detection Precision"
    ],
    "Interpretability and report generation": [
        "Report Completeness",
        "Report Quality",
        "Interpretability",
        "Result Quality",
        "Result Completeness"
    ]
}

In [ ]:
function_name = dict()
task_name = dict()
for metric in metric_list:
    for tmc in metric['TMC-list']:
        if tmc['function'] not in function_name:
            function_name[tmc['function']] = {
                "counts": 1,
                "task_dict": {},
                # "prompt_list": [],
                "task_id_list": []
            }
            function_name[tmc['function']]["task_dict"][tmc['task_name']] = 1
            # function_name[tmc['function']]["prompt_list"].append(metric['prompt'])
            function_name[tmc['function']]["task_id_list"].append(metric['name'])
        else:
            function_name[tmc['function']]['counts'] += 1
            if tmc['task_name'] not in function_name[tmc['function']]["task_dict"]:
                function_name[tmc['function']]["task_dict"][tmc['task_name']] = 1
            else:
                function_name[tmc['function']]["task_dict"][tmc['task_name']] += 1
            # function_name[tmc['function']]["prompt_list"].append(metric['prompt'])
            function_name[tmc['function']]["task_id_list"].append(metric['name'])
        
        try:
            if tmc['function'] not in task_2_func[tmc['task_name']]:
                print(metric['name'], tmc['function'], tmc['task_name'])
        except:
            print("error from ", metric['name'], tmc['function'], tmc['task_name'])

        if tmc['task_name'] not in task_name:
            task_name[tmc['task_name']] = 1
        else:
            task_name[tmc['task_name']] += 1

In [12]:
data = []

for function, values in function_name.items():
    for task, count in values["task_dict"].items():
        data.append({
            "Function": function,
            "Total Function Count": values['counts'],  # total count for this metric
            "Task": task,
            "Task Count": count,  # count for this task under the specific metric
            "Prompts": values["prompt_list"],
            "Task ID": values["task_id_list"]
        })

# Convert the list of dictionaries to a DataFrame
df = pd.DataFrame(data)

In [13]:
df.head(50)

,Function,Total Function Count,Task,Task Count,Prompts,Task ID
0,Visualization Quality,32,Data visualization,29,[Draw normal distributions for multiple 'x' an...,"[bcb659, bcb151, human_15, human_15, human_15,..."
1,Visualization Quality,32,Data exploration and statistics understand,2,[Draw normal distributions for multiple 'x' an...,"[bcb659, bcb151, human_15, human_15, human_15,..."
2,Visualization Quality,32,Pattern recognition,1,[Draw normal distributions for multiple 'x' an...,"[bcb659, bcb151, human_15, human_15, human_15,..."
3,Plot Validity,55,Data visualization,55,[Generates a pair plot from a numeric DataFram...,"[bcb983, bcb527, bcb414, human_8, bcb105, bcb3..."
4,Data Integrity,16,Data exploration and statistics understand,13,[Generates a pair plot from a numeric DataFram...,"[bcb983, bcb527, bcb105, bcb803, dl_6, bcb900,..."
5,Data Integrity,16,Data cleaning and preprocessing,3,[Generates a pair plot from a numeric DataFram...,"[bcb983, bcb527, bcb105, bcb803, dl_6, bcb900,..."
6,Prediction Accuracy,2,Data Mining,1,[Generates a pair plot from a numeric DataFram...,"[bcb983, bcb845]"
7,Prediction Accuracy,2,Data mining,1,[Generates a pair plot from a numeric DataFram...,"[bcb983, bcb845]"
8,Data Accuracy,49,Data exploration and statistics understand,48,"[""Reads data from a CSV file and generates a b...","[bcb1011, bcb162, bcb527, bcb40, bcb393, bcb87..."
9,Data Accuracy,49,Data visualization,1,"[""Reads data from a CSV file and generates a b...","[bcb1011, bcb162, bcb527, bcb40, bcb393, bcb87..."
10,Visualization Completeness,47,Data visualization,47,"[""Reads data from a CSV file and generates a b...","[bcb1011, bcb162, bcb430, bcb40, bcb1043, bcb4..."
11,Report Quality,6,Interpretability and report generation,6,"[Read a list of dictionaries from a JSON file,...","[bcb527, bcb1017, csv_excel_3, human_142, csv_..."
12,Model Accuracy,39,Predictive modeling,38,[Perform K-Means clustering on the given DataF...,"[bcb880, bcb1017, human_12, human_5, human_5, ..."
13,Model Accuracy,39,Data exploration and statistics understand,1,[Perform K-Means clustering on the given DataF...,"[bcb880, bcb1017, human_12, human_5, human_5, ..."
14,Data Consistency,25,Data cleaning and preprocessing,3,"[Merge datasets, perform KMeans clustering, th...","[bcb430, human_3, human_3, bcb54, bcb646, bcb5..."
15,Data Consistency,25,Data exploration and statistics understand,21,"[Merge datasets, perform KMeans clustering, th...","[bcb430, human_3, human_3, bcb54, bcb646, bcb5..."
16,Data Consistency,25,Data exploration and statistics understand,1,"[Merge datasets, perform KMeans clustering, th...","[bcb430, human_3, human_3, bcb54, bcb646, bcb5..."
17,Clustering Validity,14,Predictive modeling,10,"[Merge datasets, perform KMeans clustering, th...","[bcb430, human_12, bcb866, dl_6, bcb443, human..."
18,Clustering Validity,14,Data mining,4,"[Merge datasets, perform KMeans clustering, th...","[bcb430, human_12, bcb866, dl_6, bcb443, human..."
19,Normalization Range Check,15,Data cleaning and preprocessing,15,"[Calculate the Z-values of a 2D data matrix, c...","[bcb40, bcb151, bcb803, bcb1061, bcb660, bcb90..."
20,DataFrame Shape Validation,17,Data cleaning and preprocessing,17,[Remove a column from a data dictionary if it ...,"[bcb414, bcb9, bcb468, bcb209, bcb132, bcb72, ..."
21,Title Verification,15,Data visualization,15,[Create a Pandas DataFrame from a list of pair...,"[bcb9, bcb99, bcb443, bcb304, bcb134, bcb392, ..."
22,Data Cleaning Completeness,11,Data cleaning and preprocessing,11,[Please conduct a thorough examination of the ...,"[human_8, dl_6, bcb871, human_9, human_9, bcb8..."
23,Silhouette Score,5,Data mining,4,[Please conduct a thorough examination of the ...,"[human_8, human_16, csv_excel_33, human_9, dl_0]"
24,Silhouette Score,5,Pattern recognition,1,[Please conduct a thorough examination of the ...,"[human_8, human_16, csv_excel_33, human_9, dl_0]"
25,Pattern Recognition Validity,2,Pattern recognition,2,[Please conduct a thorough examination of the ...,"[human_8, human_9]"
26,Report Completeness,12,Interpretability and report generation,12,[Please conduct a thorough examination of the ...,"[human_8, human_12, human_5, csv_excel_0, huma..."
27,Data Completeness,29,Data cleaning and preprocessing,29,[Undertake an in-depth analysis of the UCI Adu...,"[human_12, csv_excel_0, csv_excel_3, bcb54, bc..."
28,Data Uniformity,7,Data exploration and statistics understand,7,[Processes a list of category labels to create...,"[bcb1043, bcb1064, bcb1078, bcb1051, csv_excel..."
29,Pattern Recognition Accuracy,1,Pattern recognition,1,[Perform KMeans clustering on a list of data p...,[bcb866]
30,Data Quality Score,66,Data cleaning and preprocessing,66,[Calculate the mean of numerical values in eac...,"[bcb870, bcb902, bcb823, human_11, dl_13, bcb4..."
31,Result Quality,5,Interpretability and report generation,5,[Calculate the mean of numerical values in eac...,"[bcb870, bcb689, bcb878, bcb815, dl_15]"
32,Data Validity,15,Data exploration and statistics understand,15,[Find the N biggest differences between the re...,"[bcb197, human_5, bcb61, bcb689, bcb359, dl_10..."
33,Result Completeness,4,Interpretability and report generation,3,[This function takes a list of tuples. The fir...,"[bcb871, bcb250, bcb361, dl_10]"
34,Result Completeness,4,Data visualization,1,[This function takes a list of tuples. The fir...,"[bcb871, bcb250, bcb361, dl_10]"
35,Explained Variance Ratio,10,Predictive modeling,10,[Perform PCA (Principal Component Analysis) on...,"[bcb877, bcb304, bcb45, bcb662, human_18, bcb6..."
36,Completeness,2,Pattern recognition,2,"[You are required to analyze the ""Credit Card ...","[human_142, human_17]"
37,Mean Squared Error,1,Predictive modeling,1,[Trains a RandomForestRegressor model and retu...,[bcb878]
38,R-squared Value,10,Predictive modeling,8,[Performs an OLS linear regression on a subset...,"[bcb750, bcb91, bcb701, bcb677, bcb690, bcb106..."
39,R-squared Value,10,Interpretability and report generation,2,[Performs an OLS linear regression on a subset...,"[bcb750, bcb91, bcb701, bcb677, bcb690, bcb106..."
40,Association Rule Count,1,Data mining,1,"[""datadir = ''\nYou are provided with a datase...",[human_17]
41,Mean Absolute Error,4,Predictive modeling,4,[Please complete the following task:\nWrite a ...,"[csv_excel_29, human_10, csv_excel_37, dl_1]"
42,Association Rule Confidence,1,Data mining,1,"[""You are required to perform a comprehensive ...",[human_7]
43,Correlation Coefficient,1,Data visualization,1,[Add a new key-value pair to the dictionary an...,[bcb262]

In [9]:
df.to_csv('function_stats.csv', index=False)